### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by throwrancer** [Zheneq/Noesis-Plugins#1]
Please forgive my poor English.

I used your plugin (fmt_fireemblem_gs.py).
When I try to open gs file with noesis
An error appears in "GSFile (NoeBitStream (data), mdlList) .load ()" on line 54.
On the other hand, I can display g file (skeleton).

(noesis is ver 4.177, python is 2.7.15 (64-bit))

The gs file I am using is FE path of radiance, uploaded below.
(An error similar to Radiant down gs file appears)
Would you please help me if possible?

http://www.mediafire.com/file/kn8nrod8muirn0x/usefile.zip/file

**Comment by Zheneq** [comment]
Fixed. It seems newer Noesis loads os module automatically or something.

**Comment by throwrancer** [comment]
I appreciate quick response.
